on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v0.6
        with:
          ruby-version: 2.7

      - name: Show seats
        id: seats
        uses: M-Yamashita01/check-members@v1
        env:
          ACCESS_TOKEN: ${{ secrets.READ_ORG_TOKEN }}
          # Set absolute directory path containing the terraform files.
          TERRAFORM_DIRECTORY_PATH: '${{ github.workspace }}/terraform/directory/path' 
          ORGANIZATION_NAME: ''

      - name: Post comments
        uses: actions/github-script@v5
        with:
          script: |
            const output = `Current filled seats and Max seats\n
              Filled seats: ${{steps.seats.outputs.filled_seats}}\n
              Max seats: ${{steps.seats.outputs.max_seats}}\n
              Member count: ${{steps.seats.outputs.members_in_terraform}}\n
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
