on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Show seats
        id: seats
        uses: M-Yamashita01/check-members@v1
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.READ_ORG_TOKEN }}
          # Set absolute file path to the terraform file containing the github_membership resources.
          # Example: '${{ github.workspace }}/membership.tf'
          MEMBERSHIP_FILE_PATH: '' 
          # Set absolute file path to the terraform file containing the github_repository_collaborator resources.
          # Example: '${{ github.workspace }}/repository_collaborator.tf'
          REPOSITORY_COLLABORATOR_FILE_PATH: ''
          ORGANIZATION_NAME: ''

      - name: Post comments
        uses: actions/github-script@v5
        with:
          script: |
            const output = `Current filled seats and Max seats\n
              Filled seats: ${{steps.seats.outputs.filled_seats}}\n
              Max seats: ${{steps.seats.outputs.max_seats}}\n
              Member count: ${{steps.seats.outputs.members_in_terraform}}\n
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
