# action.yml
name: 'Show members count'
description: 'Show members count in GitHub Organization and members in terraform files'
outputs:
  filled_seats:
    description: 'Organizations filled seats'
  seats:
    description: 'Organizations max seats'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
