# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
outputs:
  filled_seats:
    description: 'Organizations filled seats'
  seats:
    description: 'Organizations max seats'
runs:
  using: 'docker'
  image: 'Dockerfile'
