# action.yml
name: 'Show members count'
description: 'Show members count in GitHub Organization and members in terraform files'
outputs:
  filled_seats:
    description: 'Organizations filled seats'
    value: ${{ steps.member-counter.outputs.filled_seats }}
  seats:
    description: 'Organizations max seats'
    value: ${{ steps.member-counter.outputs.seats }}
runs:
  using: 'composite'
  steps:
    - id: member-counter
      run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
