# action.yml
name: 'Check Members'
description: 'This action runs on pull requests to count GitHub organization members and membership written in terraform files.'
inputs:
  verify_existence_account:
    description: 'Verify the existence of your account.'
    required: false
outputs:
  filled_seats:
    description: 'Seats that membership used.'
    value: ${{ steps.member-counter.outputs.filled_seats }}
  max_seats:
    description: 'Max seats an organization can use.'
    value: ${{ steps.member-counter.outputs.max_seats }}
  members_in_terraform:
    description: 'Total number of membership in the `github_membership` and `github_repository_collaborator` resources written in the terraform file.'
    value: ${{ steps.member-counter.outputs.members_in_terraform }}
runs:
  using: 'composite'
  steps:
    - id: member-counter
      run: |
        cd $GITHUB_ACTION_PATH
        bundle install
        ./script.sh
        cd $GITHUB_WORKSPACE
      shell: sh
branding:
  icon: 'user-check'
  color: 'red'
