# action.yml
name: 'Show members count'
description: 'Show members count in GitHub Organization and members in terraform files'
inputs:
  org_token:
    description: 'GitHub Token'
    required: true
outputs:
  filled_seats:
    description: 'Organizations filled seats'
  seats:
    description: 'Organizations max seats'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
