# action.yml
name: 'Check Member'
description: 'This action runs on pull requests to count GitHub organization members and membership written in terraform files.'
outputs:
  filled_seats:
    description: 'Seats that membership used.'
    value: ${{ steps.member-counter.outputs.filled_seats }}
  max_seats:
    description: 'Max seats an organization can use.'
    value: ${{ steps.member-counter.outputs.max_seats }}
  members_in_terraform:
    description: 'Total number of membership in the `github_membership` and `github_repository_collaborator` resources written in the terraform file.'
    value: ${{ steps.member-counter.outputs.members_in_terraform }}
runs:
  using: 'composite'
  steps:
    - id: member-counter
      run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
branding:
  icon: 'user-check'
  color: 'red'
