on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - name: Show seats
        id: seats
        uses: M-Yamashita01/OrganizationSeatsChecker@v0.1
        with:
          github_token: ${{ secrets.READ_ORG_TOKEN }}

      - name: Post comments
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'filled_seats: ${{steps.seats.outputs.filled_seats}}'
            })
