on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use local my-action
        uses: docker://organization-seats-checker:organization-seats-checker
        with:
          github_token: ${{ secrets.READ_ORG_TOKEN }}
