on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Show seats
        id: seats
        uses: M-Yamashita01/organization-seats-checker@v0.1
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.READ_ORG_TOKEN }}
          # Set absolute file path to the terraform file containing the github_membership resources.
          # Example: '${{ github.workspace }}/membership.tf'
          MEMBERSHIP_FILE_PATH: '${{ github.workspace }}/spec/fixtures/membership.tf' 
          # Set absolute file path to the terraform file containing the github_repository_collaborator resources.
          # Example: '${{ github.workspace }}/repository_collaborator.tf'
          REPOSITORY_COLLABORATOR_FILE_PATH: '${{ github.workspace }}/spec/fixtures/repository_collaborator.tf'
          ORGANIZATION_NAME: 'my-organization-sandbox'

      - name: Post comments
        uses: actions/github-script@v5
        with:
          script: |
            var output = `Current seats in organization and members in terraform files.\n
              ・Seats that memberships used:: ${{steps.seats.outputs.filled_seats}}\n
              ・Max seats an organization can use: ${{steps.seats.outputs.seats}}\n
              ・Total number of memberships in terraform files: ${{steps.seats.outputs.member_count}}\n\n
            `
            const numberOfSeatsInShortage = ${{steps.seats.outputs.member_count}} - ${{steps.seats.outputs.seats}}
            var additional_message = `There is no shortage of seats.\n`
            if (numberOfSeatsInShortage > 0) {
              additional_message = `There are ${numberOfSeatsInShortage} seats missing. Please add seats.\n`
            }
            output += additional_message

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
