on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Show seats
        id: seats
        uses: ./
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.READ_ORG_TOKEN }}
          MEMBERSHIP_FILE_PATH: '${{ github.workspace }}/spec/fixtures/membership.tf'
          REPOSITORY_COLLABORATOR_FILE_PATH: '${{ github.workspace }}/spec/fixtures/repository_collaborator.tf'

      - name: Post comments
        uses: actions/github-script@v5
        with:
          script: |
            const output = `Current filled seats and Max seats\n
              Filled seats: ${{steps.seats.outputs.filled_seats}}\n
              Max seats: ${{steps.seats.outputs.seats}}\n
              Member count: ${{steps.seats.outputs.member_count}}\n
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
