on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    name: A job to show seats
    steps:
      - name: Show seats
        uses: M-Yamashita01/OrganizationSeatsChecker@v0.1
        with:
          github_token: ${{ secrets.READ_ORG_TOKEN }}
