on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: runner / rubocop
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-review
